# Generated by Django 4.2.1 on 2023-05-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='open_poll',
            field=models.BooleanField(default=1, verbose_name='open poll'),
            preserve_default=False,
        ),
    ]
